[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yeonjae-universal-notification-service"
version = "1.0.1"
description = "Universal notification service supporting Slack, Email, Discord, and webhooks for automated reporting"
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "MIT"}
authors = [
    {name = "CodePing.AI Team", email = "contact@codeping.ai"}
]
keywords = ["notification", "slack", "email", "discord", "webhook", "alerts", "messaging", "automation"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Communications :: Email",
    "Topic :: Communications :: Chat",
    "Topic :: System :: Monitoring",
]
requires-python = ">=3.8"
dependencies = [
    "typing-extensions>=4.0.0; python_version<'3.10'",
    "requests>=2.28.0",
]

[project.optional-dependencies]
slack = [
    "slack-sdk>=3.20.0",
]
email = [
    "aiosmtplib>=2.0.0",
    "email-validator>=2.0.0",
]
discord = [
    "discord.py>=2.0.0",
]
all = [
    "slack-sdk>=3.20.0",
    "aiosmtplib>=2.0.0", 
    "email-validator>=2.0.0",
    "discord.py>=2.0.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-mock>=3.10.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
    "responses>=0.23.0",
]

[project.urls]
Homepage = "https://github.com/yeonjae-work/universal-modules"
Repository = "https://github.com/yeonjae-work/universal-modules"
Issues = "https://github.com/yeonjae-work/universal-modules/issues"
Changelog = "https://github.com/yeonjae-work/universal-modules/blob/main/packages/yeonjae-universal-notification-service/CHANGELOG.md"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
